spring.application.name=audit-service
server.port=8093


spring.datasource.url=jdbc:postgresql://localhost:5432/audit_db
spring.datasource.username=time
spring.datasource.password=timesheet
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=audit-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=com.example.common.audit.AuditEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.kafka.listener.missing-topics-fatal=false


keycloak.realm=timesheet
keycloak.auth-server-url=http://localhost:8080
keycloak.client-id=Timesheet-client
keycloak.credentials.secret=sIXDnjqCeWOq3t7bWRxIGh3M3hbKCnoO

spring.cloud.compatibility-verifier.enabled=false
