# Application Basics
spring.application.name=TimeSheet
server.port=8098

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/timesheet
spring.datasource.username=time
spring.datasource.password=timesheet
spring.datasource.driver-class-name=org.postgresql.Driver

spring.cloud.compatibility-verifier.enabled=false


# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true


identity.service.url=http://localhost:8091
logging.level.org.springframework=DEBUG
logging.level.org.keycloak=DEBUG
logging.level.com.example.timesheet=DEBUG

keycloak.realm=timesheet
keycloak.auth-server-url=http://localhost:8084
keycloak.client-id=Timesheet-client
keycloak.credentials.secret=iFuD7frY2i1lULqJ5YY4gLKLOE7xAA4P

# MailHog SMTP settings
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=

# Disable auth & TLS (MailHog doesn't need these)
#spring.mail.properties.mail.smtp.auth=false
#spring.mail.properties.mail.smtp.starttls.enable=false

#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=hasanraz189@gmail.com
#spring.mail.password=yaiq jeea nqhz ltok
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true




# Kafka Bootstrap Servers
spring.kafka.bootstrap-servers=localhost:9092

# Kafka Producer Config
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
# This is correct since you're sending Java objects as JSON.

# Kafka Consumer Config
spring.kafka.consumer.group-id=timesheet-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Optional: Don't crash if topic doesn't exist at startup
spring.kafka.listener.missing-topics-fatal=false



# Custom topic names (used in @Value injection in your services)
kafka.topic.name=timesheet-topic
kafka.topic.Json.name=timesheet-topic-Json
kafka.topic.timesheet.remainder=timesheet-remainder-topic

